version: '3'

services:
    database:
        image: postgres:14
        ports:
            - "5433:5432"
        volumes:
            - ./postgresql/data:/var/lib/postgresql/data
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: myapp_dev